server.servlet.context-path: /member
server:
  port: 8080

---

spring:
  profiles: default
  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true
      path: /h2-console
  datasource:
    generate-unique-name: false
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
  cloud:
    stream:
      kafka:
        binder:
          brokers: localhost:29092
        streams:
          binder:
            configuration:
              default:
                key:
                  serde: org.apache.kafka.common.serialization.Serdes$StringSerde
                value:
                  serde: org.apache.kafka.common.serialization.Serdes$StringSerde
      bindings:
        event-in:
          group: amf42
          destination: lecture
          contentType: application/json
        event-out:
          destination: lecture
          contentType: application/json

logging:
  level:
    org.hibernate.type: trace
    org.springframework.cloud: debug

token:
  expiration_time: 86400000
  secret: amf42_token
---

server:
  port: 8080

spring:
  profiles: docker
  cloud:
    stream:
      kafka:
        binder:
          brokers: kafka:9092
        streams:
          binder:
            configuration:
              default:
                key:
                  serde: org.apache.kafka.common.serialization.Serdes$StringSerde
                value:
                  serde: org.apache.kafka.common.serialization.Serdes$StringSerde
      bindings:
        event-in:
          group: amf42
          destination: lecture
          contentType: application/json
        event-out:
          destination: lecture
          contentType: application/json
token:
  expiration_time: 86400000
  secret: amf42_token
